<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Search by Color')) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/colorcoordinator.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-image-gallery.min.css'))
                        ->prependStylesheet('//blueimp.github.io/Gallery/css/blueimp-gallery.min.css')
                        ->prependStylesheet($this->basePath('css/bootstrap-colorpicker.min.css'))
                        ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css')
                        ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css')
        ; ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap-image-gallery.min.js'))
            ->prependFile('//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js')
            ->prependFile($this->basePath('js/bootstrap-colorpicker.min.js'))
            ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js')
            ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
        ; ?>

    </head>
    <body>

        <div class="jumbotron">
            <div class="container">
                <?php echo $this->content; ?>
            </div>
        </div>


        <?php echo $this->inlineScript()
            ->prependFile($this->basePath('js/colorcoordinator.js'))
        ; ?>


    </body>
</html>
