<h1 class="display-3">Search by Color</h1>

<p>You can search Ranjan Sen's art by color using the color picker below.
The vertical bar picks the hue, and the square box adjusts the saturation.</p>

<p>(Want more color ideas? Try this
<a target="_blank" href="http://www.decorlove.com/how-to-choose-a-color-scheme-the-basics-of-color-coordination/">
intro to color in interior decorating</a>.)</p>

<!-- Bootstrap Colorpicker (https://github.com/mjolnic/bootstrap-colorpicker) -->
<div id="colorpicker" class="inl-bl"></div>

<p id="gallery-prompt" class="gallery-prompt"></p>

<!-- Boilerplate HTML skeleton for the Bootstrap Image Gallery (https://github.com/blueimp/Bootstrap-Image-Gallery) -->
<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Images for the image gallery -->
<div id="links">
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
    <a href="" title="" data-gallery>
        <img src="" alt="">
    </a>
</div>

