<h1 class="display-3">Search by Color</h1>

<p>You can search Ranjan Sen's art by color using the color picker below.
The vertical bar picks the hue, and the square box adjusts the saturation.</p>

<p>(Want more color ideas? Try this
    <a target="_blank" href="http://www.decorlove.com/how-to-choose-a-color-scheme-the-basics-of-color-coordination/">
        intro to color in interior decorating</a>.)</p>

<div id="colorpicker" class="inl-bl"></div>

<script>
    $(function() {
        // Set up Bootstrap colorpicker (http://mjolnic.com/bootstrap-colorpicker/)
        $('#colorpicker').colorpicker({
            color: '#625194',
            container: true,
            inline: true,
            format: 'hex',
            customClass: 'colorpicker',
            sliders: {
                saturation: {
                    maxLeft: 200,
                    maxTop: 200
                },
                hue: {
                    maxTop: 200
                }
            }
        });

        $('#colorpicker').colorpicker().on('changeColor', function (e) {
            console.log("Chose color: " + e.color.toHex());
        });
    });
</script>

<p id="gallery-prompt-found" class="gallery-prompt">Here is the matching art. Select a thumbnail to see a larger image.</p>
<p id="gallery-prompt-none-found" class="gallery-prompt">No matching works found. Please try another color.</p>

<!-- Set up the Bootstrap Image Gallery (https://github.com/blueimp/Bootstrap-Image-Gallery) -->
<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="links">
    <a href="/img/art/Jerusalem.jpg" title="Jerusalem" data-gallery>
        <img src="/img/art/thumbs/Jerusalem.jpg" alt="Jerusalem">
    </a>
    <a href="/img/art/Hong_Kong.JPG" title="Hong_Kong" data-gallery>
        <img src="/img/art/thumbs/Hong_Kong.JPG" alt="Hong_Kong">
    </a>
    <a href="/img/art/Huleh.jpg" title="Huleh" data-gallery>
        <img src="/img/art/thumbs/Huleh.jpg" alt="Huleh">
    </a>
</div>

